### ISSUE TITLE
试用之后题几点问题建议

### ISSUE THREAD

**Issue by lanthree** [StickCui/XDUthesis-personal#1]
首先非常感谢，此模板是我看到的本科模板中可用性最高的
### 几点问题建议

---
1. ![](http://7b1exv.com1.z0.glb.clouddn.com/QQ%E6%88%AA%E5%9B%BE20160408165152.png)这里的“Key Words”应该是“Key words”
2. ![](http://7b1exv.com1.z0.glb.clouddn.com/QQ%E6%88%AA%E5%9B%BE20160408165010.png)这里黑体部分的英文并没有黑体，同样如果论文标题里有英文的话，也不会被黑体。可能是你直接用的`\heiti`只支持中文的原因。
   我这里重新引进英文黑体`\newfontfamily\enheiti{SimHei}`，然后用`\newcommand\multiheiti{\heiti\enheiti}`，替代`\heiti`，不知道是否合理。
3. 封面，之前看齐飞教授模板的时候看到，封面没有logo的问题，建议封面去掉logo
4. 代码环境感觉略难看，建议代码字体 `Source Code Pro`，高亮有四项，颜色参考[Tomorrow Theme](https://github.com/ChrisKempson/Tomorrow-Theme)
5. 我对自己修改的模板能不能放出来不太清楚，所以麻烦你来改下吧，我就不放出来了。

**Comment by StickCui** [comment]
## lanthree 同学你好

---

### 根据你的意见，我对照着我校的《本科生毕业设计（论文）工作手册》（以下简称学生手册）进行了查验，阅读并编译了齐飞教授的模板，现回复如下：

---
1. 英文关键词“**Key words**”确实是我定义错了，十分感谢你的指正。
2. 关于摘要部分的中英文关键词，相关规定见《学生手册》第9-10页；英文关键词要求“Times News Roman”字体，加粗，小四号；通过阅读后面附的一些样例，发现在中文关键词出现的英文，第一份样例还是用的“Times News Roman”的粗体，和全文要求一致（英文一律采用“Times News Roman”字体），所以本人上不明确，在中文关键词中是否要强制将英文设置为黑体加粗。
3. 这里的logo我主要参考了学校教务处提供的封面模板，logo问题值得商榷，可以考虑做个可选参数，屏蔽掉。（齐飞老师的模板我从来没有正确编译出来过，可能跟我用的TeXLive2015 whose package had been updated有关），今天看了下，老师的模板又更新了，在两个月前，然而我还是编译样例不完全成功。
4. 代码字体是我当时参加美赛的时候，从别人的模板里借鉴过来的，感觉挺好看就用了；（之前想用“Courier New”字体来着，但是设置略麻烦，可能有些用户的电脑上还没有这个字体，就放弃了）也十分感谢你的建议。
5. 你自己修改的，欢迎放出来，大家共同进步。本人的一些想法，已经写在回复你的邮件里了。（邮件里的一些观点都是看到邮件后马上回复的，有些可能不太准确，望见谅）

**Comment by lanthree** [comment]
1. 关于摘要部分，确实第一分样例用的"Times News Roman"，但是对比你的模板生成的Main.pdf的中英文摘要会发现，中文摘要的英文单词没有被加粗，这里也许可以修改一下。
2. 关于封面的标题，这点我没说清楚，封面标题里的英文参考第一个样例的话是被强制黑体了。在此模板中是“Times News Roman”。
3. 齐飞教授的模板的话，我是在release里下的`xduthesis-1.0.0-b2-source.tar.gz`，里面有完整例子，但是要装几个字体才可以编译OK。我也是用的texlive2015。
4. 代码
   ![](http://7xsomc.com2.z0.glb.clouddn.com/50B485A7C23FEE230F3D4EB02FF5EFE0.png)，可能大家喜欢的风格不一样。不过都不知道合不合规范...
5. 我是这周二才接触LaTeX的，请多指教！

PS：非常感谢

**Comment by StickCui** [comment]
OK，了解了，感谢你的指正。这些细节我都没有注意到，也期待你把你的模板发布出来。还有，代码字体很好看。
![image](https://cloud.githubusercontent.com/assets/12728028/14401133/31af2b98-fe39-11e5-8773-c2898328df6a.png)

**Comment by lanthree** [comment]
我fork了这个项目，并提交了代码，有兴趣的话可以看下，汝若以后发现什么问题希望提醒。

**Comment by lanthree** [comment]
其实还有个也许要修改的地方，
因为之前老师说我软必须要Word，而且也没看在你有更新，就再在这提了。。。。
就是：

行间距

虽然setstretch 1.5被了，但是 要求上说是以Word参考的1.5背间距。对比可以发现行间距不够的，因为两者定义行间距的方式不一样，为了同Word一样，setstretch大概要设置到1.7左右。

**Comment by StickCui** [comment]
谢谢提醒，这个问题我当时也疑惑过，一些大牛们的博客以及LaTeX书籍中提到Word中的行间距指的是行距因子，LaTeX中的行距还再看；当初设置这个值的时候是根据刘海洋写的书设置的，后来就忘了。

后期会关注一下，再此感谢提醒

**Comment by StickCui** [comment]
我特地试了一下，首先说一下，行距的概念，**行距=行距因子x基本行距**；其中基本行距为当前字号的1.2倍。

其实，Word中所说的几倍行距说的是行距因子，按照这种理解，本人模板现在的设置`\setstretch{1.5}`是没有问题的；但是，我在word中写的一些文字（设置成1.5倍行距）后，生成的PDF中行距为1.96左右，也就是说Word实际设置的行距因子约为1.63333；这就很尴尬了！

紧接着，我试着将LaTeX中的行距因子改为了1.63，结果竟然和word一样了。这确实很尴尬！我现在犹豫要不要修改后再次提交了。233333333

**Comment by XDXX** [comment]
@StickCui 行距的设置的问题现在有答案了吗？

**Comment by StickCui** [comment]
差不多了 暂定 1.62 我比对了下 差别不大。另外，新的版本刚刚已经提交了，加了个可选参数

**Comment by XDXX** [comment]
@StickCui 为什么我用本模板生成的pdf文件中的每章的标题比word里的粗很多？

**Comment by StickCui** [comment]
@XDXX 不会吧，你将word转成PDF后对比的？？？

**Comment by XDXX** [comment]
@StickCui 对啊，我是将word转换成word对比的
![](https://ooo.0o0.ooo/2016/05/13/5735c8a10500f.png)
![](https://ooo.0o0.ooo/2016/05/13/5735c8a27c152.png)
那个比较粗的就是用latex生成的，细的是word的。
我用的是最新版模板的默认设置。

**Comment by StickCui** [comment]
@XDXX 我试了试，发现确实是粗的，在PDF编辑中显示为加粗，但是我对其选中后加粗再撤销，就变正常了，我怀疑标题项ctex宏集默认加粗了

**Comment by XDXX** [comment]
@StickCui 我发现这个章标题加粗的问题是由于在 cls 文件中对章标题的格式设置中将 `nameformat` 和 `titleformat` 分开设置导致的。如果只设置全局格式 `format` 的话将不会出现这个问题。

**Comment by StickCui** [comment]
@XDXX 我最初写这个模板的时候，这样设置根本不起作用，在我更新ctex宏集后有神奇的可以了。严重怀疑当时我电脑出问题了！感谢指正。
关于提交的PR的一些意见已经在那个 Pull requests 下给出了，希望修改下谢谢！感谢你的无私奉献！！！
