### ISSUE TITLE
make.cmd 的问题

### ISSUE THREAD

**Issue by BDZNH** [StickCui/XDUthesis-personal#10]
这个应该是`git`的问题，提交的时候会自动把行尾改成unix风格。我这里下载之后，直接点击`make.cmd`会出现命令不可用的提示。

![image](https://user-images.githubusercontent.com/17548735/56959295-86513b80-6b7f-11e9-85c6-91f5f1ae936f.png)

**Comment by StickCui** [comment]
@BDZNH 感谢提醒，你要不说我都忘了这事儿了，这是 Windows 版本 Git 的坑，我这边电脑里还关不掉。
换到Ubuntu系统下暂时修复了。
