### ISSUE TITLE
有几个疑惑的点

### ISSUE THREAD

**Issue by BDZNH** [StickCui/XDUthesis-personal#12]
# 页面布局的问题

我看手册上写的是`以WORD97为例：页面设置数据为：上，下，内侧，外侧；装订线——1厘米；页眉——2厘米；页脚——1厘米`

如果我没弄错的话，在你的模板中，页面数据在这里XDUthesis.cls文件内的

```
\RequirePackage[a4paper,left=4cm,right=2cm,top=3cm,bottom=2cm]{geometry}
```
这里的对应关系我确实没弄明白，这里的页面数据为“上、下、内侧、外侧“，是在”对称页边距“和”书籍折页“中(如下图)才有的选项，但是手册上并没有写页边距是多少。仅仅写了页眉页脚装订线。

![image](https://user-images.githubusercontent.com/17548735/57003357-b557c380-6bf8-11e9-9ce9-32ce4e513465.png)

我疑惑的点在于`left=4cm,right=2cm,top=3cm,bottom=2cm`这里的数据如何确定。

# 章节标题间距的问题
这里可能有点绕，手册内没有明确写出章节标题与下一行的距离，也没有明确段见距，也就是段前段后。所以我想知道你的模板内对这两个距离是如何确定的。

我是这样想的，手册没有明说，那么按正文处理，比如章（chapter）标题为黑体三号，那么它离下一行的距离就是三号字体的`1.5`倍(Latex模板启动word行距,也就是1.62)。小节标题也如此。段间距按正文处理。

![image](https://user-images.githubusercontent.com/17548735/57003333-66aa2980-6bf8-11e9-9235-36df09823409.png)

如上图，上面是用word，下面是编译好的pdf，我把页面缩放到差不多大小，看起来Latex编译后的文件，章(chapter)名的间距更大一些。

我的疑惑点在于：模板内对这里的距离的设置是以哪里为准，如果是以我上面描述的以word设置的格式为准的话，那么是不是模板内的参数设置有问题。

# readme.md 文件内的问题

如下图
![image](https://user-images.githubusercontent.com/17548735/57003418-29926700-6bf9-11e9-9f78-071dcfcf09e8.png)

图中的链接是失效的，正确的链接是
封面模板：[http://sjjx.xidian.edu.cn/down/html/?18.html](http://sjjx.xidian.edu.cn/down/html/?18.html)
诚信声明书模板没看见。

**Comment by BDZNH** [comment]
第一个第二个问题没有针对你的意思，你的模板是我见过做得最完善的，很强。

**Comment by StickCui** [comment]
@BDZNH 
# 关于第一个问题
手册给的上下内外的距离就是页边距，由于是双页模式（书籍折页），因此这里的 left 对应的就是内侧，right对应的就是外侧，之所以left是4cm是因为有1cm的装订线距离。

此外，因为我比较懒，所以当初写模板的时候没有想其他高校模板那样，专门弄一个print参数，共打印论文的时候使用（此时才会加上装订线距离在内测，无该参数的时候会把装订线距离平均分在两侧，便于撰写时以及电子版提交时的阅读）。我直接默认就是打印版本。因为就16年及以前的情况来看，本科生的毕业设计论文是不需要提交电子版的。

# 关于第二个问题
这个应该是由于手册里面没有规定，我就没单独设置，用的是 ctex 宏集默认定义的。如果有影响的话可以通过下面的命令调整
``` LaTeX
\ctexset{
  chapter/afterskip={18pt} % 示例距离
}
```

# 关于第三个问题
这个链接自我毕业后就上不去了，仅限校内网用户访问，我也没办法。你提的PR已经Merge到master了。

**Comment by BDZNH** [comment]
@StickCui 
刚刚找到诚信声明书的链接了，已经发起pr

# 对于第一个问题

如下图

![image](https://user-images.githubusercontent.com/17548735/57007703-43de3c00-6c1d-11e9-8c9c-1656bbc7552b.png)

刚刚发现，学校发给我们的手册是错的，oh~~~~

刚刚找到了电子版工作手册

![image](https://user-images.githubusercontent.com/17548735/57007725-6e2ff980-6c1d-11e9-854d-5de67bb4a2f7.png)

**Comment by BDZNH** [comment]
这个 issue 可以关了。

**Comment by StickCui** [comment]
@BDZNH 同学不好意思，我这边正在进行 README 的重新排版，这次的 PR 就没法接受了，我把你的链接加上去了，同时也加了致谢。希望你能理解，这个issue就关了。

**Comment by BDZNH** [comment]
没问题

**Comment by GuoPingPan** [comment]
请问每个chapter的title距离页眉线留白太宽怎么调整?

还有摘要的标题部分也是

![image](https://user-images.githubusercontent.com/69315544/236160430-bfaac2e9-dfd8-4428-9d7d-729e637e999c.png)
![image](https://user-images.githubusercontent.com/69315544/236161115-cb60414e-2bba-41c8-b718-17af479d4ac5.png)
![image](https://user-images.githubusercontent.com/69315544/236161277-4721df1c-f4c3-4744-9653-54511593bb50.png)

**Comment by BDZNH** [comment]
> 请问每个chapter的title距离页眉线留白太宽怎么调整?
> 
> 还有摘要的标题部分也是
> 
> ![image](https://user-images.githubusercontent.com/69315544/236160430-bfaac2e9-dfd8-4428-9d7d-729e637e999c.png) ![image](https://user-images.githubusercontent.com/69315544/236161115-cb60414e-2bba-41c8-b718-17af479d4ac5.png) ![image](https://user-images.githubusercontent.com/69315544/236161277-4721df1c-f4c3-4744-9653-54511593bb50.png)

@GuoPingPan 我这里没有环境验证，不过 titile 到 content 的距离是通过
```
\ctexset{
  chapter/afterskip={18pt} % 示例距离
}
```
调整，你看看是否也可以通过添加类似 `beforeskip`的方式来调整 title 到页眉之间的距离。

**Comment by GuoPingPan** [comment]
试了一下好像并不可以
