### ISSUE TITLE
做了一点调整

### ISSUE THREAD

**Issue by BDZNH** [StickCui/XDUthesis-personal#15]
详细说明在提交的 comment 里面

## 电子版预览样式
[https://github.com/BDZNH/XDUthesis-personal/commit/05e99acd463dd29498c23a697a8cfdcfe525bdac](https://github.com/BDZNH/XDUthesis-personal/commit/05e99acd463dd29498c23a697a8cfdcfe525bdac)

## 修正封面右上角班级学号的行距
[https://github.com/BDZNH/XDUthesis-personal/commit/b7dd0f836d7db43b720ef01edbfc4eef558c11ad](https://github.com/BDZNH/XDUthesis-personal/commit/b7dd0f836d7db43b720ef01edbfc4eef558c11ad)

**Comment by StickCui** [comment]
@BDZNH PR 已合并
