### ISSUE TITLE
生成的pdf中，英文字体复制到word会乱码的问题

### ISSUE THREAD

**Issue by Acmenwangtuo** [StickCui/XDUthesis-personal#19]
将生成的英文字母进行复制，会生成如下

⑄⑥⑮⑳⑥⑎⑥⑴

**Comment by StickCui** [comment]
@Acmenwangtuo 请提供编译的具体环境以及具体的配置，比如下图的字体配置以及编译的引擎
![image](https://user-images.githubusercontent.com/12728028/81402181-81946f80-9163-11ea-99cb-47bba03cec01.png)

**Comment by Acmenwangtuo** [comment]
字体乱码问题在重新编译之后已经解决，但是还有一个疑问：

<img width="388" alt="a50ab2259cf3dea416f8e6cbd433267" src="https://user-images.githubusercontent.com/25858179/81402649-64ac6c00-9164-11ea-9bd5-5192089ffa62.png">
<img width="348" alt="447dba6a82f66cbbc3fe71dc1d465be" src="https://user-images.githubusercontent.com/25858179/81402670-6e35d400-9164-11ea-8dcf-fb68df5babda.png">
上图是latex 模板之间的间距，下图是word的间距 怎样调整 章标题 和页眉之间的距离呢 感谢

**Comment by StickCui** [comment]
@Acmenwangtuo 请参考下图以及 ctex 包的说明（命令行执行 `textdoc ctex`），在 `XDUthesis.cfg` 对应部分进行修改
![image](https://user-images.githubusercontent.com/12728028/81405964-45650d00-916b-11ea-8f20-5966b2851a50.png)

**Comment by Acmenwangtuo** [comment]
我更改20 重新执行cmd脚本 没有变化。。。

**Comment by Acmenwangtuo** [comment]
感谢，查看ctex开发文档之后，加上`fixskip = true`就可以删去多余的空格，建议可以更新上

**Comment by StickCui** [comment]
@Acmenwangtuo 感谢你的使用与建议，之后有时间我会再次更新一版，有其它问题，也欢迎随时开 issue，这个 issue 我先关掉了
