### ISSUE TITLE
考虑增加Linux/Mac兼容性

### ISSUE THREAD

**Issue by DelightRun** [StickCui/XDUthesis-personal#2]
由于我本人只有Macbook可用，所以在考虑为本项目增加Mac兼容，不知可否？

**Comment by XDXX** [comment]
@DelightRun 你知道咱们计算机学院的毕设确定可以用 LaTex 吗？查重什么的不影响吧？

**Comment by lanthree** [comment]
我在Mac mini上用的完全没问题啊

**Comment by DelightRun** [comment]
@XDXX 我导师说可以。

**Comment by DelightRun** [comment]
@lanthree 嗯是的，我只是加了个Makefile
