### ISSUE TITLE
关于参考文献引用上标的问题

### ISSUE THREAD

**Issue by zay1817** [StickCui/XDUthesis-personal#24]
![例子](https://github.com/StickCui/XDUthesis-personal/assets/161465779/3b82fb74-a5c1-43ed-a64a-56a0085ab8cb)
请问为什么使用这个模板时，引用参考文献上标数字比较粗、比较扁并且没有在右上角？应该怎么修改呢？

**Comment by StickCui** [comment]
> ![例子](https://private-user-images.githubusercontent.com/161465779/335768186-3b82fb74-a5c1-43ed-a64a-56a0085ab8cb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczODcwNDgsIm5iZiI6MTcxNzM4Njc0OCwicGF0aCI6Ii8xNjE0NjU3NzkvMzM1NzY4MTg2LTNiODJmYjc0LWE1YzEtNDNlZC1hNjRhLTU2YTAwODVhYjhjYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QwMzUyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWExNzY0ZjZmNDczY2ZhMGY1ODZlODczMGNlNmZhNzBkNzkwNTE3ZDdiZDU5YjNhZDZmN2VhOTViNmY0ODMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.coAcWpgjGpjaSSpvmstkqo3ZnkxGWgNTVRwAXjwJzl8) 请问为什么使用这个模板时，引用参考文献上标数字比较粗、比较扁并且没有在右上角？应该怎么修改呢？

可以使用`\onlinecite{}` 命令，达到目的
