### ISSUE TITLE
什么时候添加《手册》缺失的几个项目

### ISSUE THREAD

**Issue by Cupwell** [StickCui/XDUthesis-personal#4]
与《手册》对比，好像缺失了《工作计划》、《中期检查表》、《成绩考核登记表》、《结束语》（可选）、《结论》（可选），虽然这几页可以用word弄好再夹上去，希望能添加上这几页吧。
另外，中英文摘要的空白页不要有页眉吧，好像不太好看。

**Comment by lanthree** [comment]
前三个是学校打印好发的吧。。。我也不太清楚

**Comment by StickCui** [comment]
《工作计划》等这几个表弹性太大；主要原因是有些表需要盖章后才能一起装订的；正文中可以不需要这些表。

这些表可以一一打印出来，改签名的签名，该盖章的盖章，等学院审核结束后，再随着论文一起装订
