### ISSUE TITLE
\subsubsection 距离问题

### ISSUE THREAD

**Issue by XDXX** [StickCui/XDUthesis-personal#5]
@StickCui 
我用这个模板生成的pdf中\subsubsection与周围环境的距离有问题，有的距离正确有的距离过大。
比如这里的距离就过大。![距离过大](https://ooo.0o0.ooo/2016/05/08/5730178017a64.png)
而下面的距离就正常![距离正常](https://ooo.0o0.ooo/2016/05/08/5730182150eaa.png)

**Comment by StickCui** [comment]
这里是LaTeX底层的排版规则定的与`\subsubsection`命令无关，而且不仅仅限于`\subsubsection`命令；

有时候当页内容放不下接下来的标题（章、节、小节等等），会把标题以下的内容放到下一页，而对当页的内容进行段落间距拉伸。word也会这样，不过处理的貌似是页面下边空白，很难看
