### ISSUE TITLE
一些格式问题

### ISSUE THREAD

**Issue by yabostone** [StickCui/XDUthesis-personal#6]
用了很久，自己也做了些修改，不过还有有些问题。
- tableofcontents   章节那里要加dot，参见蓝皮书。XDBA版的印象里也有newcommands。
- 参考文献中每个引用之间的间隔太长。
- 字体的问题发现已经改正。

**Comment by XDXX** [comment]
@git4xuan 你说的字体的问题具体是指什么问题？

**Comment by yabostone** [comment]
- 之前的英文摘要部分，不是规定字体，现查阅已改正。就是说三四个月前不是Norman字体。
- 使用的代码部分，使用了多种字体，和蓝皮书不符合，全部去除。
- Keywords中间没有空格，此外冒号后方留有一个空格的间距。
-  目录部分，每个章节后面没有加点，这里已经是被要求严重改正。

**Comment by yabostone** [comment]
齐飞老师的模板是有什么问题没？
今天特意加了要求字体试了一下，没有发现格式问题啊？

**Comment by XDXX** [comment]
齐飞老师的那个模板我没有用过，我不知道那个模板的具体情况。那个目录里章节和页码间添加 dots 的问题我已经找到方法了，我回到宿舍可以给你发一下。最近
StickCui 同学好像一直没太上 GitHub。

mingxuan notifications@github.com于2016年5月16日周一 下午6:46写道：

**Comment by yabostone** [comment]
了解了，谢啦哈，学习下写法。
再说下封面吧，封面好像是统一发的，后面写。logo下面的字容易到下一面去，我当时换字体的时候就出现多次，当时直接调整了间距，把logo和下面的box的间距减小了。

**Comment by yabostone** [comment]
能发份对应修改的dtx文件或者cls和cfg文件么？我的邮箱git4xuan#gmail.com(替换#)。非常感谢。

刚才看了下版面，齐飞老师的模板还是有些对应不上，像论文上方都写“论文”二字。

**Comment by yabostone** [comment]
`\setmainfont{Times New Roman}`
这个要uncommit，或者使用
`\usepackage{times}`.
修订，dtx文件为\Requirepackage{times}

**Comment by StickCui** [comment]
@git4xuan @XDXX 感谢二位的指正。前几天一直在家，没网；今天刚回学校。
- 封面部分，其实我没打算做为论文要是用的部分，仅是展示（封面等表格学校官方给了）；仅此，就是用了最笨的方法来控制位置。
- 英文字体部分，严格来看的话，是属于罗马字体族，但使用Fandol字体族时默认严格不是Times New Roman字体，看着十分接近而已。这个我没来得及弄(-_-|||)
- 目录的章部分和页码之间没有`\dot`的问题，我最开始就注意到了，但是在蓝皮书的要求里没有说一定要有点，只是给的例子里都有而已，我还一直在纠结。

此外，当时做这些东西为了偷懒，能用ctex默认设置的都用默认了。我改………………

**Comment by yabostone** [comment]
- 图片显示冒号问题，\RequirePackage[labelsep=quad]{caption}[2011/11/10]   % 图片的部分格式
- 字体格式部分  %% \setmainfont{Times New Roman} 要去除commit，否则代码部分非要求字体，Abstract也非要求字体。
- 封面处的间距vspace可以调至4em,这样不会出现封面占用两面的情形。

review问题：
- 无法判定最后的参考文献引用是否按照IEEE的格式规范。
- 目录处建议参考xudthsis的部分，好像连\dot的数量也考虑到了，还有文字的类别，比例。
  现查看时确实参考文献没有设置好间距。典型的\itemsep为-2mm或-1mm。这块没有看模板文件。

---

@StickCui 强烈建议修订参考文献部分的间距，我已经不想看cls和dtx了。。
求问老师对格式的要求这么松么。。
我是一个个的盯着改的，每天都挤时间改这东西。
个人就不做 Pull Requests了。

---

补充一下，最后的格式要求其实是要模仿Word，换句话说交Word版本，这边说\dot问题是重要的格式问题，包括参考文献的间距和内容是否按照IEEE的格式书写。我这边提到的问题都是比较重要的问题，盲审这方面没好可能直接打回。应该说完全按照蓝皮书的要求来。

**Comment by StickCui** [comment]
@git4xuan 同学，你提到的这些问题很宝贵，感谢你的指正。

## 关于参考文献

参考文献部分学校官方给的小蓝书里没有明确规定使用何种参考文献样式，只是给了专著类和期刊类的排列格式。你说的IEEE的参考文献样式我目前只在齐飞老师的模板里介绍说要使用。
此外，学校官方小蓝书里给的三个论文样例里面参考文献有些也没有按照要求（该是点分割用了逗号），要求不超过3个作者，却写了4个（见手册36页）。综上，参考文献样式要求不太严。样式修改很简单，我模板里给了两个（其实是一个）参考的文献样式文件（bst），如果不满意，随时可以更换为（IEEEtran）就是一条指令的事。
此外，参考文献的间距部分，我确实没找到哪里有规定，除了字号，其他默认，劳烦给予具体说明下，感谢！

## 关于目录

目录中的点的要求，后续确实可以填上这个坑。

## 关于全文字体

会把commit去掉。再次感谢！！

## 最后

由于我还要抽时间修改论文，上面这些坑可能无法及时填上！但会尽快，学校的校园网对github很不友好，导致我不能想在北京那样及时进行更新，抱歉！

**Comment by yabostone** [comment]
- 参考文献的问题理解了，主要说的是Latex在默认情况下每个引用间会额外增加间距，其他的关系不大。我也不想再进行改动了。
- 论文的问题最近确实需要增加些时间。
