### ISSUE TITLE
空白页

### ISSUE THREAD

**Issue by argsno** [StickCui/XDUthesis-personal#8]
为什么我在Windows 10+Latex 2015上编译的时候每一章后面都会出现一页空白页

**Comment by argsno** [comment]
应该是我写的都是奇数页的问题，但是可以加个选项选择去掉那些页吗？

**Comment by StickCui** [comment]
这个是正常的，学校的学生手册上要求，章必须出现在奇数页；如果前面章的内容不足偶数页，则LaTeX的book文档类型会自动多插入一页空白页（仍有页眉），以保证后续的章出现在奇数页上。

此外，给你说下实现原理，在声明或复写 `\chapter`命令时，会在前面多加一个 `\cleardoublepage` 命令，该命令会检查前面的页码是否为偶数页，是则等同于 `\clearpage` 命令，否则，会多加一页空白页，然后等同于 `\clearpage` 命令。

**Comment by argsno** [comment]
Thank you

**Comment by argsno** [comment]
根据我在知网上看到的论文（一篇清华大学的博士论文）来看，似乎并没有出现这样的要求。
